# Generated by Django 4.2.11 on 2024-04-23 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fan_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_advertisements', to=settings.AUTH_USER_MODEL),
        ),
    ]
