# Generated by Django 4.2.11 on 2024-04-24 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan_site_app', '0002_advertisement_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='response',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='fan_site_app.advertisement'),
        ),
    ]
